### PR TITLE
Allow different icons (blade icons)

### PR DESCRIPTION
**Pull request by Enaah**
Hey man,

I've used (and tweaked) your package in my application and want to give the feature to customize the iconsset back to this package.

Since Laravel devs often use the quite uprising  [Bladeicons](https://github.com/blade-ui-kit/blade-icons) Iconset (with Tailwind often in combination with the [Heroicons](https://github.com/blade-ui-kit/blade-heroicons)), I expanded the behavior to allow this.

Let me know if you would like to change anything.

Have a nice day! ✌🏽

_Edit:_ This is a **Breaking Change** because the config must be republished/edited!

### CODE REVIEW

**Comment by mattlibera** [comment]
Thanks @Enaah ! I appreciate the contribution. I'll try and give this a look this weekend.

**Comment by Enaah** [comment]
Any thoughts on this?
This implementation may not ne the best, but blade-icons support would be great.
(Or you go Blade only, because you can use Font-Awesome with this package: https://github.com/owenvoke/blade-fontawesome)

**Comment by mattlibera** [comment]
Hey @Enaah , sorry it's taken me so long to get back to you. I'm looking at this vs. #24 and I believe that solution would actually handle this idea as well. Basically if the views were made publishable then you could simply sub in whatever you want.

Plus, that approach actually fixes issue #23 which is legit; the Tailwind classes shouldn't be injected in the way I'm doing it (whoops).

I'll close this for now since that PR looks like a more permanent, flexible solution. Thanks for using my package!

**Comment by Enaah** [comment]
Nice!
Thank you for this package 🙂

**Pull request closed without merging**
